blank_issues_enabled: false
contact_links:
  - name: Rocketseat Discord
    url: https://rocketseat.com.br/comunidade
    about: Ask questions, get help and discuss new things you're building with the Gatsby community
