name: Deploy docs

on: push
jobs:
  build:
    name: Build Gatsby Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build Docs Site
        uses: jzweifel/gatsby-cli-github-action@master
        env: GATSBY_PROJECT_PATH = "./www"
        with:
          gatsby-arg: build
